#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${1:-${AUDIT_BASE_URL:-http://127.0.0.1:3000}}"
TS="$(date +%Y%m%d-%H%M%S)"
OUT_DIR="reports"
OUT_FILE="${OUT_DIR}/site-audit-${TS}.md"

mkdir -p "$OUT_DIR"

check_code() {
  local path="$1"
  local expected="$2"
  local code
  code=$(curl -sS -o /dev/null -w "%{http_code}" -m 10 "${BASE_URL}${path}" || true)
  if [[ "$code" == "$expected" ]]; then
    echo "✅ ${path} -> ${code}"
  else
    echo "❌ ${path} -> ${code} (expected ${expected})"
  fi
}

{
  echo "# Site Audit Report"
  echo
  echo "- Base URL: ${BASE_URL}"
  echo "- Time: $(date -Iseconds)"
  echo
  echo "## Runtime health"
  check_code "/api/health" "200"
  check_code "/" "200"
  check_code "/login" "200"
  echo
  echo "## Anonymous access control"
  check_code "/api/crm/customers" "401"
  check_code "/api/appeals" "401"
  code=$(curl -sS -o /tmp/session-${TS}.json -w "%{http_code}" -m 10 "${BASE_URL}/api/auth/session" || true)
  if [[ "$code" == "200" ]]; then
    if grep -q "{}\|null" /tmp/session-${TS}.json; then
      echo "✅ /api/auth/session anonymous returns empty session"
    else
      echo "⚠️ /api/auth/session anonymous is non-empty, verify auth behavior"
    fi
  else
    echo "❌ /api/auth/session -> ${code}"
  fi
  echo
  echo "## Summary"
  echo "- Report generated by scripts/site-audit.sh"
} | tee "$OUT_FILE"

echo
echo "Report saved: $OUT_FILE"
